'coarse_language':
  'patterns':
  - '\bpottsau\b'
  - '\bschachtel\b'
  - '\bschlamp\w*\b'
  - '\blusche\b'
  - '\blapp(en)?\b'
  - '\btrantüte\b'
  - '\bpflaume\b'
  - '\bhohle\s+nuss\b'
  - '\btrottel\w*\b'
  - '\bdepp\w*\b'
  - '\bam\s+arsch\s+der\s+welt\b'
  - '\b(stock|stockig)\s+im\s+arsch\b'
  - '\bgeht\s+doch\b'
  - '\b(das|des)\s+schreckens\b'
  - '\bgelaber\b'
  - '\bkacke\b'
  - '\bglotzen\b'
  - '\b(ver)?kackt\w*\b'
  - '\bverarschen\b'
  - '\bverarscht\b'
  - '\bverpissen\b'
  - '\bverpiss dich\b'
  - '\bhackt es bei (dir|euch|ihnen)\b'
  - '\b(?:voll)?(?:scheiße|kacke|mist|dreck|schrott)\b'
