'expressive_para_noise':
  'patterns':
  - '[!?]{4,}'
  - '(?<!\d)1{2,}!{2,}|!{2,}1{2,}(?!\d)'
  - '\b[!?]{2,}[A-Za-z]?[!?]{2,}\b'
  - '(?-i:\b[A-ZÄÖÜ]{3,}[!?]{2,})'
  - '(?:\w+\s*(?:[\U0001F300-\U0001FAFF]{2,})|(?:[\U0001F300-\U0001FAFF]{2,})\s*\w+)'
  - '(?m)^(?-i:[A-ZÄÖÜ0-9!? ]+)$\n^(?-i:[A-ZÄÖÜ0-9!? ]+)$'
  - '(?m)(?-i:\b[A-ZÄÖÜ]{3,}(?:\.[^\S\r\n]+[A-ZÄÖÜ]{2,}){1,}\.?)'
  - '(?u)(?<![\w.])(?:[A-Za-zÄÖÜäöüß]\s+){3,}[A-Za-zÄÖÜäöüß](?![\w.])'
  - '(?u)(?<![\w.])(?:[A-Za-zÄÖÜäöüß]\s+){2,}[A-Za-zÄÖÜäöüß](?:\s{2,}(?:[A-Za-zÄÖÜäöüß]\s+){2,}[A-Za-zÄÖÜäöüß})+(?![\w.])'
  - '[\u2600-\u27BF]{3,}'
  - '[\U0001F300-\U0001F6FF]{3,}'
  - '[\U0001F900-\U0001F9FF]{3,}'
  - '(?:💩|❤️|🤣|😂|😍|🤪|😘|😡|😅){3,}'
  - '[\u2600-\u27BF\U0001F300-\U0001FAFF]{3,}'
  - '(?:❤|🙏|😍|👍|💖|💎|✨|👏|🐬|🔥){3,}'
  - '[\U0001F300-\U0001F6FF][A-Za-z0-9ÄÖÜäöü\- ]{1,40}[\U0001F300-\U0001F6FF]'
  - '\b\w*(\w)\1{3,}\w*\b'
  - '\b\w*[aeiouäöüAEIOUÄÖÜ]{4,}\w*\b'
  - '\b\w*[aeiouäöüAEIOUÄÖÜ]{2,}[!?]{2,}\b'
  - '[!?]{3,}'
