'socio_moral_heroism':
  'patterns':
  - '\bWork-Life-Balance\b'
  - '\bWeiterentwicklung\b'
  - '\bEntfaltungspotenzial\b'
  - '\bwertschätzend(?:e|er|es)?\b'
  - '\bTeamplayer\b'
  - '\bflache Hierarchien\b'
  - '\bkollegiales Umfeld\b'
  - '\bUnternehmenskultur\b'
  - '\bEigenverantwortung\b'
  - '\bHands-on-Mentalität\b'
  - '\bkommunikativ(?:e|er|es)?\b'
  - '\bProblemlösungskompetenz\b'
  - '\bbewerben Sie sich jetzt\b'
  - '\bwir freuen uns auf Ihre Bewerbung\b'
  - '\battraktives Paket\b'
  - '\bflexible Arbeitszeiten\b'
  - '\bVision(?:en|är|äre)?\b'
  - '\bzukunftsweisend\b'
  - '\binnovativ(?:e|er|es)?\b'
  - '\bNext Level\b'
  - '\bdefinieren.*neu\b'
  - '\bwir sind stolz\b'
  - '\bwir glauben\b'
  - '\bunsere Werte\b'
  - '\bwertesystem\b'
  - '\bnachhaltig\b'
  - '\bverantwortungsvoll\b'
  - '\bLieferkette\b'
