'vulgar_speech':
  'exclusions':
  - '\b(reptil(oid)?|echse|tierwelt|biologie|spezies)\b'
  - '\b(anatomie|fortpflanzung|begattung|paarung)\b'
  - '\b(wirbel|schuppe|klaue|gebiss)\b'
  - '\b(urologie|untersuchung|befund)\b'
  'patterns':
  - '\bfick\w*\b'
  - '\bfotz\w*\b'
  - '\bscheiß\w*\b'
  - '\barsch\w*\b'
  - '\bpimm\w*\b'
  - '\bwichs\w*\b'
  - '\bhur(?:e|en|er|erei|ig)?\b'
  - '\bnutte\w*\b'
  - '\bfresse\b'
  - '(?i)\bmusch(?:i|is|ia)\b'
  - '\bmös\w*\b'
  - '\bkack\w*\b'
  - '\bkotz\w*\b'
  - '\bdrecks\w*\b'
  - '\btitt\w*\b'
  - '\bnippel\w*\b'
  - '\bleckmich\w*\b'
  - '\bverpiss\w*\b'
  - '\bfuck\w*\b'
  - '\bshit\w*\b'
  - '\bbitch\w*\b'
  - '\bdummes+vieh\b'
